[package]
name = "procon2d-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rusb = "0.9"
hidapi = { version = "2", features = ["linux-static-hidraw"] }
uinput = "0.1.3"
anyhow = "1"
once_cell = "1"
env_logger = "0.11.8"
